default_platform(:ios)

before_all do
  ensure_git_status_clean
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']
    match(type: "appstore", readonly: is_ci)

    build_app(
      workspace: "ios/App/App.xcworkspace",
      scheme: "App",
      export_method: "app-store",
      output_directory: "./build/ios"
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Deploy to App Store"
  lane :release do
    setup_ci if ENV['CI']
    match(type: "appstore", readonly: is_ci)

    build_app(
      workspace: "ios/App/App.xcworkspace",
      scheme: "App",
      export_method: "app-store",
      output_directory: "./build/ios"
    )

    upload_to_app_store(
      force: true,
      submit_for_review: false
    )
  end
end

platform :android do
  desc "Build and deploy to Play Store internal track"
  lane :beta do
    gradle(
      project_dir: "android",
      task: "bundle",
      build_type: "Release"
    )

    upload_to_play_store(
      track: "internal",
      aab: "android/app/build/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true
    )
  end

  desc "Deploy to Play Store production"
  lane :release do
    gradle(
      project_dir: "android",
      task: "bundle",
      build_type: "Release"
    )

    upload_to_play_store(
      track: "production",
      aab: "android/app/build/outputs/bundle/release/app-release.aab"
    )
  end
end
